// Generated by gencpp from file aqua_gazebo/ThrustParams.msg
// DO NOT EDIT!


#ifndef AQUA_GAZEBO_MESSAGE_THRUSTPARAMS_H
#define AQUA_GAZEBO_MESSAGE_THRUSTPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace aqua_gazebo
{
template <class ContainerAllocator>
struct ThrustParams_
{
  typedef ThrustParams_<ContainerAllocator> Type;

  ThrustParams_()
    : header()
    , K1(0.0)
    , K2(0.0)  {
    }
  ThrustParams_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , K1(0.0)
    , K2(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _K1_type;
  _K1_type K1;

   typedef double _K2_type;
  _K2_type K2;




  typedef boost::shared_ptr< ::aqua_gazebo::ThrustParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aqua_gazebo::ThrustParams_<ContainerAllocator> const> ConstPtr;

}; // struct ThrustParams_

typedef ::aqua_gazebo::ThrustParams_<std::allocator<void> > ThrustParams;

typedef boost::shared_ptr< ::aqua_gazebo::ThrustParams > ThrustParamsPtr;
typedef boost::shared_ptr< ::aqua_gazebo::ThrustParams const> ThrustParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aqua_gazebo::ThrustParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aqua_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'aqua_gazebo': ['/home/shabirmean/Desktop/COMP765/Assignment1/src/aqua_gazebo/msg', '/home/shabirmean/Desktop/COMP765/Assignment1/src/aqua_gazebo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aqua_gazebo::ThrustParams_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aqua_gazebo::ThrustParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aqua_gazebo::ThrustParams_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e0e2b6bc7942aa373465fb1cd44868e";
  }

  static const char* value(const ::aqua_gazebo::ThrustParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e0e2b6bc7942aa3ULL;
  static const uint64_t static_value2 = 0x73465fb1cd44868eULL;
};

template<class ContainerAllocator>
struct DataType< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aqua_gazebo/ThrustParams";
  }

  static const char* value(const ::aqua_gazebo::ThrustParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64 K1\n\
float64 K2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::aqua_gazebo::ThrustParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.K1);
      stream.next(m.K2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrustParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aqua_gazebo::ThrustParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aqua_gazebo::ThrustParams_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "K1: ";
    Printer<double>::stream(s, indent + "  ", v.K1);
    s << indent << "K2: ";
    Printer<double>::stream(s, indent + "  ", v.K2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUA_GAZEBO_MESSAGE_THRUSTPARAMS_H
