// Auto-generated. Do not edit!

// (in-package aquacore.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ChangeDepthFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percent_depth_change_completed = null;
    }
    else {
      if (initObj.hasOwnProperty('percent_depth_change_completed')) {
        this.percent_depth_change_completed = initObj.percent_depth_change_completed
      }
      else {
        this.percent_depth_change_completed = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ChangeDepthFeedback
    // Serialize message field [percent_depth_change_completed]
    bufferOffset = _serializer.float64(obj.percent_depth_change_completed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ChangeDepthFeedback
    let len;
    let data = new ChangeDepthFeedback(null);
    // Deserialize message field [percent_depth_change_completed]
    data.percent_depth_change_completed = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'aquacore/ChangeDepthFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fb4840ab3fac3d08d9262a1a6b1c2c09';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Feedback
    float64 percent_depth_change_completed
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ChangeDepthFeedback(null);
    if (msg.percent_depth_change_completed !== undefined) {
      resolved.percent_depth_change_completed = msg.percent_depth_change_completed;
    }
    else {
      resolved.percent_depth_change_completed = 0.0
    }

    return resolved;
    }
};

module.exports = ChangeDepthFeedback;
