// Auto-generated. Do not edit!

// (in-package aquacore.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoSurfaceTaskFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.task = null;
      this.percent_depth_change_completed = null;
      this.has_reached_constant_depth = null;
      this.has_established_gps = null;
    }
    else {
      if (initObj.hasOwnProperty('task')) {
        this.task = initObj.task
      }
      else {
        this.task = 0;
      }
      if (initObj.hasOwnProperty('percent_depth_change_completed')) {
        this.percent_depth_change_completed = initObj.percent_depth_change_completed
      }
      else {
        this.percent_depth_change_completed = 0.0;
      }
      if (initObj.hasOwnProperty('has_reached_constant_depth')) {
        this.has_reached_constant_depth = initObj.has_reached_constant_depth
      }
      else {
        this.has_reached_constant_depth = false;
      }
      if (initObj.hasOwnProperty('has_established_gps')) {
        this.has_established_gps = initObj.has_established_gps
      }
      else {
        this.has_established_gps = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoSurfaceTaskFeedback
    // Serialize message field [task]
    bufferOffset = _serializer.byte(obj.task, buffer, bufferOffset);
    // Serialize message field [percent_depth_change_completed]
    bufferOffset = _serializer.float64(obj.percent_depth_change_completed, buffer, bufferOffset);
    // Serialize message field [has_reached_constant_depth]
    bufferOffset = _serializer.bool(obj.has_reached_constant_depth, buffer, bufferOffset);
    // Serialize message field [has_established_gps]
    bufferOffset = _serializer.bool(obj.has_established_gps, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoSurfaceTaskFeedback
    let len;
    let data = new DoSurfaceTaskFeedback(null);
    // Deserialize message field [task]
    data.task = _deserializer.byte(buffer, bufferOffset);
    // Deserialize message field [percent_depth_change_completed]
    data.percent_depth_change_completed = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [has_reached_constant_depth]
    data.has_reached_constant_depth = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [has_established_gps]
    data.has_established_gps = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 11;
  }

  static datatype() {
    // Returns string type for a message object
    return 'aquacore/DoSurfaceTaskFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3fb53b8f9ad6654cf096432b41609bf3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Feedback
    byte task                                # see SurfaceTaskTypes.msg
    float64 percent_depth_change_completed
    bool has_reached_constant_depth
    bool has_established_gps
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoSurfaceTaskFeedback(null);
    if (msg.task !== undefined) {
      resolved.task = msg.task;
    }
    else {
      resolved.task = 0
    }

    if (msg.percent_depth_change_completed !== undefined) {
      resolved.percent_depth_change_completed = msg.percent_depth_change_completed;
    }
    else {
      resolved.percent_depth_change_completed = 0.0
    }

    if (msg.has_reached_constant_depth !== undefined) {
      resolved.has_reached_constant_depth = msg.has_reached_constant_depth;
    }
    else {
      resolved.has_reached_constant_depth = false
    }

    if (msg.has_established_gps !== undefined) {
      resolved.has_established_gps = msg.has_established_gps;
    }
    else {
      resolved.has_established_gps = false
    }

    return resolved;
    }
};

module.exports = DoSurfaceTaskFeedback;
