// Auto-generated. Do not edit!

// (in-package aquacore.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class GotoFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_waypoint = null;
    }
    else {
      if (initObj.hasOwnProperty('current_waypoint')) {
        this.current_waypoint = initObj.current_waypoint
      }
      else {
        this.current_waypoint = new geometry_msgs.msg.Pose();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GotoFeedback
    // Serialize message field [current_waypoint]
    bufferOffset = geometry_msgs.msg.Pose.serialize(obj.current_waypoint, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GotoFeedback
    let len;
    let data = new GotoFeedback(null);
    // Deserialize message field [current_waypoint]
    data.current_waypoint = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 56;
  }

  static datatype() {
    // Returns string type for a message object
    return 'aquacore/GotoFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1996e7f170eaa92091d553f10efda1ee';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Feedback 
    
    # Current position and orientation. 
    # Semantics as above.
    geometry_msgs/Pose current_waypoint
    
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GotoFeedback(null);
    if (msg.current_waypoint !== undefined) {
      resolved.current_waypoint = geometry_msgs.msg.Pose.Resolve(msg.current_waypoint)
    }
    else {
      resolved.current_waypoint = new geometry_msgs.msg.Pose()
    }

    return resolved;
    }
};

module.exports = GotoFeedback;
