// Auto-generated. Do not edit!

// (in-package aquacore.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class GotoGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_waypoint = null;
      this.start_towards_last_bearing = null;
    }
    else {
      if (initObj.hasOwnProperty('target_waypoint')) {
        this.target_waypoint = initObj.target_waypoint
      }
      else {
        this.target_waypoint = new geometry_msgs.msg.Pose();
      }
      if (initObj.hasOwnProperty('start_towards_last_bearing')) {
        this.start_towards_last_bearing = initObj.start_towards_last_bearing
      }
      else {
        this.start_towards_last_bearing = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GotoGoal
    // Serialize message field [target_waypoint]
    bufferOffset = geometry_msgs.msg.Pose.serialize(obj.target_waypoint, buffer, bufferOffset);
    // Serialize message field [start_towards_last_bearing]
    bufferOffset = _serializer.bool(obj.start_towards_last_bearing, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GotoGoal
    let len;
    let data = new GotoGoal(null);
    // Deserialize message field [target_waypoint]
    data.target_waypoint = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset);
    // Deserialize message field [start_towards_last_bearing]
    data.start_towards_last_bearing = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 57;
  }

  static datatype() {
    // Returns string type for a message object
    return 'aquacore/GotoGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5fbff635c879e970e24112664f7e3eb1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Desired goal
    
    # (x,y) denotes latitude and longitude respectively (in degrees)
    # z denotes depth, > 0 above the water, 0 on the surface, < 0 underwater (in meters)
    # orientation is currently not handled 
    geometry_msgs/Pose target_waypoint
    
    # True if we want to avoid a random step to initialize the global heading of the robot 
    # and instead use the last known heading from the previous goal. 
    # This is useful when we have a chain of goals to reach, one after the other, because
    # it avoids ugly turns in the beginning of the trajectory towards the next goal..
    bool   start_towards_last_bearing 
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GotoGoal(null);
    if (msg.target_waypoint !== undefined) {
      resolved.target_waypoint = geometry_msgs.msg.Pose.Resolve(msg.target_waypoint)
    }
    else {
      resolved.target_waypoint = new geometry_msgs.msg.Pose()
    }

    if (msg.start_towards_last_bearing !== undefined) {
      resolved.start_towards_last_bearing = msg.start_towards_last_bearing;
    }
    else {
      resolved.start_towards_last_bearing = false
    }

    return resolved;
    }
};

module.exports = GotoGoal;
