# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aquacore/GetStateRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetStateRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "aquacore/GetStateRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetStateRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aquacore/GetStateResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import aquacore.msg
import std_msgs.msg

class GetStateResponse(genpy.Message):
  _md5sum = "eed0983a56703471598bb1e571d9dddf"
  _type = "aquacore/GetStateResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """StateMsg state


================================================================================
MSG: aquacore/StateMsg
Header header
int32 LED
int32 Gait

float32 RollAngle
float32 PitchAngle
float32 YawAngle

float32 RollTargetAngle
float32 PitchTargetAngle
float32 YawTargetAngle
float32 DepthTarget

float32 AvgRollCommand
float32 AvgPitchCommand
float32 AvgYawCommand
float32 AvgHeaveCommand
float32 AvgSurgeCommand

int32 AutopilotMode
float32 Depth
float32 Speed

float32[] LegCurrents


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['state']
  _slot_types = ['aquacore/StateMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetStateResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = aquacore.msg.StateMsg()
    else:
      self.state = aquacore.msg.StateMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs))
      _x = self.state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i12fi2f().pack(_x.state.LED, _x.state.Gait, _x.state.RollAngle, _x.state.PitchAngle, _x.state.YawAngle, _x.state.RollTargetAngle, _x.state.PitchTargetAngle, _x.state.YawTargetAngle, _x.state.DepthTarget, _x.state.AvgRollCommand, _x.state.AvgPitchCommand, _x.state.AvgYawCommand, _x.state.AvgHeaveCommand, _x.state.AvgSurgeCommand, _x.state.AutopilotMode, _x.state.Depth, _x.state.Speed))
      length = len(self.state.LegCurrents)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.state.LegCurrents))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.state is None:
        self.state = aquacore.msg.StateMsg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.state.LED, _x.state.Gait, _x.state.RollAngle, _x.state.PitchAngle, _x.state.YawAngle, _x.state.RollTargetAngle, _x.state.PitchTargetAngle, _x.state.YawTargetAngle, _x.state.DepthTarget, _x.state.AvgRollCommand, _x.state.AvgPitchCommand, _x.state.AvgYawCommand, _x.state.AvgHeaveCommand, _x.state.AvgSurgeCommand, _x.state.AutopilotMode, _x.state.Depth, _x.state.Speed,) = _get_struct_2i12fi2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.state.LegCurrents = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs))
      _x = self.state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i12fi2f().pack(_x.state.LED, _x.state.Gait, _x.state.RollAngle, _x.state.PitchAngle, _x.state.YawAngle, _x.state.RollTargetAngle, _x.state.PitchTargetAngle, _x.state.YawTargetAngle, _x.state.DepthTarget, _x.state.AvgRollCommand, _x.state.AvgPitchCommand, _x.state.AvgYawCommand, _x.state.AvgHeaveCommand, _x.state.AvgSurgeCommand, _x.state.AutopilotMode, _x.state.Depth, _x.state.Speed))
      length = len(self.state.LegCurrents)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.state.LegCurrents.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.state is None:
        self.state = aquacore.msg.StateMsg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.state.header.seq, _x.state.header.stamp.secs, _x.state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.state.LED, _x.state.Gait, _x.state.RollAngle, _x.state.PitchAngle, _x.state.YawAngle, _x.state.RollTargetAngle, _x.state.PitchTargetAngle, _x.state.YawTargetAngle, _x.state.DepthTarget, _x.state.AvgRollCommand, _x.state.AvgPitchCommand, _x.state.AvgYawCommand, _x.state.AvgHeaveCommand, _x.state.AvgSurgeCommand, _x.state.AutopilotMode, _x.state.Depth, _x.state.Speed,) = _get_struct_2i12fi2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.state.LegCurrents = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i12fi2f = None
def _get_struct_2i12fi2f():
    global _struct_2i12fi2f
    if _struct_2i12fi2f is None:
        _struct_2i12fi2f = struct.Struct("<2i12fi2f")
    return _struct_2i12fi2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
class GetState(object):
  _type          = 'aquacore/GetState'
  _md5sum = 'eed0983a56703471598bb1e571d9dddf'
  _request_class  = GetStateRequest
  _response_class = GetStateResponse
