# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aquacore/AutopilotModes.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AutopilotModes(genpy.Message):
  _md5sum = "aaf40c41586272cf417462aa78a8b3a1"
  _type = "aquacore/AutopilotModes"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 OFF = 0
int32 ANGLES = 2
int32 DEPTH = 4 # depth-regulated AP includes angle-regulation as well

# The following are for 3D autopilot (see aquaautopilot ROS package)
int32 AP_OFF = 0
int32 AP_GLOBAL_ANGLES_LOCAL_THRUST = 2
int32 AP_GLOBAL_ANGLES_FIXED_DEPTH = 4
int32 AP_FIRST_INVALID_AP_MODE = 5
"""
  # Pseudo-constants
  OFF = 0
  ANGLES = 2
  DEPTH = 4
  AP_OFF = 0
  AP_GLOBAL_ANGLES_LOCAL_THRUST = 2
  AP_GLOBAL_ANGLES_FIXED_DEPTH = 4
  AP_FIRST_INVALID_AP_MODE = 5

  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AutopilotModes, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
