// Generated by gencpp from file aquacore/SetString.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETSTRING_H
#define AQUACORE_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <aquacore/SetStringRequest.h>
#include <aquacore/SetStringResponse.h>


namespace aquacore
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetString > {
  static const char* value()
  {
    return "64e58419496c7248b4ef25731f88b8c3";
  }

  static const char* value(const ::aquacore::SetString&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetString > {
  static const char* value()
  {
    return "aquacore/SetString";
  }

  static const char* value(const ::aquacore::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetStringRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetString > 
template<>
struct MD5Sum< ::aquacore::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetString >::value();
  }
  static const char* value(const ::aquacore::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetStringRequest> should match 
// service_traits::DataType< ::aquacore::SetString > 
template<>
struct DataType< ::aquacore::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetString >::value();
  }
  static const char* value(const ::aquacore::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetStringResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetString > 
template<>
struct MD5Sum< ::aquacore::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetString >::value();
  }
  static const char* value(const ::aquacore::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetStringResponse> should match 
// service_traits::DataType< ::aquacore::SetString > 
template<>
struct DataType< ::aquacore::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetString >::value();
  }
  static const char* value(const ::aquacore::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETSTRING_H
